import type { Metadata } from 'next';
import { Recursive } from 'next/font/google';
import './globals.css';

const fontRecursive = Recursive({
	variable: '--font-recursive',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={fontRecursive.className}
			suppressHydrationWarning={true}
			data-lt-installed='true'
		>
			<body className='bg-(--bg-color) overflow-x-hidden'>{children}</body>
		</html>
	);
}
